  - name: installing dependencies
    apt:
      name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      update_cache: yes
      
  - name: Get docker GPG key for auth
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Adding docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
  
  - name: Installing docker
    apt: 
      name: docker-ce
      state: latest
      update_cache: yes

