--- 
networks: 
  sfia_network: 
    driver: overlay
services: 
  service_1: 
    deploy: 
      replicas: 3
    image: denzaaaaal/service_1
    networks: 
      - ingress
  service_2: 
    deploy: 
      replicas: 3
    image: denzaaaaal/service_2
    networks: 
      - ingress
  service_3: 
    deploy: 
      replicas: 3
    image: denzaaaaal/service_3
    networks: 
      - ingress
  service_4: 
    deploy: 
      replicas: 3
    image: denzaaaaal/service_4
    networks: 
      - ingress
  web_server: 
    deploy: 
      replicas: 3
    image: denzaaaaal/web_proxy
    networks: 
      - ingress
    ports: 
      - "80:80"
version: "3.7"
