--- 
    services: 
      service_1:
        image: denzaaaaal/service_1
        networks:
          - ingress
        env_file: cloud_database.env
        deploy:
          replicas: 3

      service_2:
        image: denzaaaaal/service_2
        networks:
          - ingress
        deploy:
          replicas: 3

      service_3: 
        image: denzaaaaal/service_3
        networks:
          - ingress
        deploy:
          replicas: 3

      service_4:
        image: denzaaaaal/service_4 
        networks:
          - ingress
        deploy:
          replicas: 3
      
      web_server:
        image: denzaaaaal/web_proxy
        ports:
          - "80:80"
        networks:
          - ingress
        deploy:
          replicas: 3
          
    networks:
      ingress:
        driver: overlay

    version: "3.7"