- hosts: manager
  become: true
  tasks:
    - name: deploy as swarm
      command: docker stack deploy --compose-file docker_compose_swarm.yml stackdemo
      args:
        chdir: /var/lib/jenkins/workspace/sfia2/services